name: Java CI/CD with Heroku Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run Tests
        run: mvn test

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: "java-santhus"
        run: |
          # Authenticate with Heroku
          echo "$HEROKU_API_KEY" | heroku login --api-key
          
          # Deploy using Git (modern auth)
          git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git || true
          git push heroku HEAD:main --force
